name: Tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    tags-ignore:
      - v*
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        node: [ '16', '18' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm test
